import { Attribute } from '../types/SustainabilityReportTypes';

type AttributeTemplate = {
  name: string;
  attributes: Attribute[];
};

export const AttributeTemplates: AttributeTemplate[] = [
  {
    name: 'Sustainability Report',
    attributes: [
      {
        id: '1',
        name: 'Carbon Footprint (CO2 Emissions)',
        description:
          'This metric measures the total amount of greenhouse gases (GHG), primarily carbon dioxide (CO2), emitted directly and indirectly by the company over a specific period. It is often reported in metric tons of CO2 equivalent (CO2e) and can be broken down into Scope 1 (direct emissions), Scope 2 (indirect emissions from energy), and Scope 3 (other indirect emissions).',
      },
      {
        id: '2',
        name: 'Energy Consumption',
        description:
          "This metric tracks the total amount of energy used by the company, usually reported in gigajoules (GJ) or megawatt-hours (MWh). It often includes both renewable and non-renewable energy sources, allowing stakeholders to assess the company's energy efficiency and reliance on sustainable energy sources.",
      },
      {
        id: '3',
        name: 'Water Usage',
        description:
          'This metric measures the total volume of water consumed by the company in its operations, typically reported in cubic meters (m³). It may include details on water withdrawal, water recycling, and water discharge, highlighting the company’s impact on local water resources and its efforts to manage water sustainably.',
      },
      {
        id: '4',
        name: 'Waste Generation',
        description:
          'This metric quantifies the total amount of waste generated by the company, often categorized as hazardous, non-hazardous, or recyclable waste. It may include details on waste disposal methods, recycling rates, and waste reduction initiatives, reflecting the company’s commitment to waste management and circular economy principles.',
      },
      {
        id: '5',
        name: 'Renewable Energy Use',
        description:
          'This metric assesses the proportion of renewable energy sources in the company’s energy mix, such as solar, wind, hydro, or geothermal power. It may be reported as a percentage of total energy consumption or in absolute terms, reflecting the company’s transition to cleaner and more sustainable energy sources.',
      },
    ],
  },
];
